## Set change log file for your documents
#CHANGELOG="../debian/changelog"
#
#doc_rev=`head -1 #{CHANGELOG} | sed -e "s/^\\S*\\s\\+(\\([0-9]*:\\)\\?\\(\\S\\+\\)).*/\\2/"`
#doc_datestring=`grep "^ -- .* <.*>  .\\+$" #{CHANGELOG} | head -1 | sed -e "s/^.\\+>  \\(.\\+\\)$/\\1/g"`
#doc_date=`date -d "#{doc_datestring}" +"%Y-%m-%d %H:%M:%S"`
#ENV["DOC_REV"]=ENV["DOC_REV"]? ENV["DOC_REV"] : doc_rev.strip
#ENV["DOC_DATE"]=ENV["DOC_DATE"]? ENV["DOC_DATE"] : doc_date.strip

require 'docbones'
source_suffix = '.rst'
::Docbones.setup source_suffix

PROJ.root= "."
PROJ.name = "dev-guide"
PROJ.index = "dev-guide"
PROJ.output = "../output/dev-guide"
PROJ.css_path = "/stylesheet/lightbox/nf.lightbox.css,/stylesheet/ossxp/doc.css"
PROJ.js_path = "/javascript/jquery/1.4.2.js,/javascript/lightbox/nf.lightbox.js,/javascript/lightbox/load-nf.lightbox.js"
PROJ.pdf_style = "/opt/ossxp/conf/pdf/ossxp.style"
PROJ.default_dpi = 120

task:default do
  sh 'rake -T'
end
